version: 2
updates:
  - package-ecosystem: "pip" # Python (pip) dependencies
    directory: "/" # Location of requirements.txt or setup.py
    schedule:
      interval: "weekly" # Can be "daily", "weekly", or "monthly"
